project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"

website:
  title: "Biology 101"
  twitter-card:
    card-style: summary_large_image
    description: "Biology 101"
  page-footer:
    left: "This page was built with ❤️, [R](https://cran.r-project.org) and [Quarto](https://quarto.org/) by Marco Chiapello."
  navbar:
    background: "#447099"
    logo: "materials/images/albert.jpg"
    left:
      - text: Slides
        menu: 
          - href: materials/M1_intro.qmd
            text: "Modulo I: Introduzione al corso"
          - href: https://phd-toolbox-course.github.io/2022_PhD_Toolbox_course/M4_RicercaRiproducibile.html#1
            text: "Modulo II: Ricerca Riproducibile"
          - href: https://datacarpentry.org/spreadsheet-ecology-lesson/
            text: "Modulo III: L'organizzazione dei dati"
          - href: materials/M3_introR.qmd
            text: "Modulo IV: Cosa sono R e RStudio?"
      - href: materials/risorse.qmd
        text: "Materiale aggiuntivo"
      - href: https://revelotraining.slack.com
        text: "Slack chat"
      - href: https://drive.google.com/drive/folders/1jLnkacbeItPUl6gIdWrf2EAQoaEBQM6R?usp=share_link
        text: "Cartella condivisa"
      - text: Mappe concettuali
        menu: 
          - href: materials/images/R.pdf
            text: "R"
          - href: materials/images/variable.pdf
            text: "Variabile in R"
          - href: materials/images/vector.pdf
            text: "Vettore in R"
          - href: materials/images/Dataframe.pdf
            text: "Dataframes"
          - href: materials/images/tibble.pdf
            text: "Tibble"
    right: 
      - text: "Revelo DataLabs"
        href: https://revelodatalabs.com
      - icon: github
        href: https://github.com/mchiapello/202305_REVELO_TorVergata_Intro2R

format:
  html:
    theme: 
      - litera
      - style.css
    toc: true
